# -*- coding: utf-8 -*-
"""IA _Conversor_KM/h-M/s.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WLdhRXLOaPF3GwD8wSG6nklNPr2ZmJTR
"""

import tensorflow as tf
import numpy as np

KMh = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])
Ms = np.array([2.77778, 4.16667, 5.55556, 6.94444, 8.33333, 9.72222, 11.1111, 12.5, 13.8889])

capa = tf.keras.layers.Dense(units=1, input_shape=[1])
modelo = tf.keras.Sequential([capa])

modelo.compile(
    optimizer=tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

print("Comenzando entrenamiento...")
historial = modelo.fit(KMh, Ms, epochs=1000, verbose=False)
print("Modelo entrenado.")

import matplotlib.pyplot as plt
plt.xlabel("Epoca")
plt.ylabel("Magnitud de perdida")
plt.plot(historial.history["loss"])

print("hagamos una prediccion!")
resultado = modelo.predict([40.0])
print("El resultado es" + str(resultado) + "Metros segundo")