DROP DATABASE IF EXISTS KADOO;

CREATE DATABASE KADOO;

USE KADOO;

/*Creación tabla TCENTR*/
CREATE TABLE /*IF NOT EXISTS*/ TCENTR (
  NUMCE    TINYINT UNSIGNED PRIMARY KEY,
  NOMCE    VARCHAR(30),
  SENAS    VARCHAR(40));

/*Creación tabla TDEPTO*/
CREATE TABLE /*IF NOT EXISTS*/ TDEPTO (
  NUMDE    INTEGER UNSIGNED PRIMARY KEY,
  NUMCE    TINYINT UNSIGNED,
  DIREC    INTEGER UNSIGNED,
  TIDIR    ENUM ('P','F'),
  PRESU    DECIMAL (12,2),-- UNSIGNED,
  DEPDE    INTEGER UNSIGNED, -- DEFAULT NULL,
  NOMDE    VARCHAR(20));

/*Creación tabla TEMPLE*/
CREATE TABLE /*IF NOT EXISTS*/ TEMPLE (
  NUMEM INTEGER UNSIGNED PRIMARY KEY,
  NUMDE INTEGER UNSIGNED,
  EXTEL SMALLINT UNSIGNED,
  FECNA DATE,
  FECIN DATE,         CHECK (YEAR(FECIN) >= (YEAR(FECNA) + 18)),
  SALAR DECIMAL(7,2)  CHECK (SALAR >= 600),
  COMIS NUMERIC(6,2)  CHECK (COMIS >=100 AND COMIS <=1000),
  NUMHI TINYINT       CHECK (NUMHI BETWEEN 0 AND 10),
  NOMEM VARCHAR(20));







