CALL kadoo.siDivisible(4, 2);
CALL kadoo.notasPrimaria(5, 'Laura Pérez');
CALL kadoo.sumaNumerosPares();
CALL kadoo.sumaNumerosPares2();
CALL kadoo.sumaPrimerosNumerosNaturales();
CALL kadoo.operacionesAritméticas(2, 6);
CALL kadoo.primeros20Impares();
CALL kadoo.fechaLarga('02-08-2023');
CALL kadoo.empleadosPorDpto(100);
CALL kadoo.empleadosPorCentro(10);
CALL kadoo.dirpresuPorDpto(100, @director, @presupuesto);
SELECT @director, @presupuesto;