-- 1
SELECT NOMDE
FROM TDEPTO
JOIN TEMPLE ON TDEPTO.DIREC = TEMPLE.NUMEM
WHERE TDEPTO.TIDIR = 'F'
ORDER BY NOMDE;

-- 2
SELECT NUMEM, NOMEM, EXTEL
FROM TEMPLE
WHERE NUMDE = 121
ORDER BY NOMEM;

-- 3
SELECT EXTEL
FROM TEMPLE
ORDER BY EXTEL;

-- 4
SELECT NOMEM, SALAR, COMIS
FROM TEMPLE
WHERE NUMHI > 3
ORDER BY COMIS, NOMEM;

-- 5
SELECT NOMEM, SALAR
FROM TEMPLE
WHERE NUMHI = 0
ORDER BY SALAR DESC, NOMEM;

-- 6
SELECT CONCAT('Departamento de ', NOMDE) AS "Departamento"
FROM TDEPTO
WHERE PRESU < 300000
ORDER BY NOMDE;

-- 7
SELECT NUMDE, NOMDE, CONCAT(FORMAT(PRESU + (PRESU / 12) * 0.10, 2), ' €') AS "Presupuesto Anual Total"
FROM TDEPTO
WHERE (PRESU / 12) > 3000
ORDER BY NOMDE;
