use kadoo;

SELECT COUNT(TEMPLE.NUMEM) as NUM_EMPLEADOS, SUM(TEMPLE.SALAR + TEMPLE.COMIS + TEMPLE.NUMHI) as TOTAL_SALARIOS
FROM TDEPTO
INNER JOIN TEMPLE ON TDEPTO.NUMDE = TEMPLE.NUMDE
WHERE TEMPLE.SALAR > 2400
GROUP BY TDEPTO.NUMDE;

SELECT MIN(TEMPLE.SALAR) as SALARIO_MINIMO, AVG(TEMPLE.SALAR) as SALARIO_MEDIO, MAX(TEMPLE.SALAR) as SALARIO_MAXIMO
FROM TDEPTO
INNER JOIN TEMPLE ON TDEPTO.NUMDE = TEMPLE.NUMDE
WHERE TEMPLE.FECIN < DATE_SUB(NOW(), INTERVAL YEAR(NOW()) - YEAR(TEMPLE.FECIN) YEAR)
GROUP BY TDEPTO.NUMDE
HAVING AVG(TEMPLE.FECIN) > (YEAR(NOW()) - YEAR(TEMPLE.FECIN));