use kadoo;

/*Funciones escalares*/

-- 1
SELECT COUNT(*) AS NumDeptos,
AVG(PRESU) AS PresupuestoAnualMedio
FROM TDEPTO;

-- 2
SELECT AVG(DATEDIFF(CURDATE(), FECIN)/365) AS MediaAniosServicio
FROM TEMPLE
WHERE NUMDE IN (111, 112);

-- 3
SELECT AVG(DATEDIFF(FECIN, '1986-12-31')/365) AS MediaAniosServicio
FROM TEMPLE 
WHERE NUMDE IN (111, 112);

-- 4 
SELECT NOMEM, (SALAR + COMIS) AS SalarioTotal
FROM TEMPLE 
WHERE (SALAR + COMIS) > (SELECT 1800 + MIN(SALAR + COMIS)FROM TEMPLE);

-- 5
SELECT AVG(DATEDIFF(FECIN, DATE_SUB(CURDATE(), INTERVAL 30 YEAR))/365) AS EdadMediaIngreso 
FROM TEMPLE;

-- 6
SELECT SUM((SALAR + COMIS) * 14) AS MasaSalarialAnual 
FROM TEMPLE;

-- 7
SELECT COUNT(*) AS NumIngresados 
FROM TEMPLE 
WHERE YEAR(FECIN) = 1978;

-- 8
SELECT AVG(SALAR + COMIS) AS SalarioMedio 
FROM TEMPLE 
WHERE SALAR <= (SELECT 1.2 * MIN(SALAR) FROM TEMPLE WHERE NUMHI > 0);

-- 9 
SELECT AVG(DATEDIFF(CURDATE(), FECNA)/365) AS EdadMedia 
FROM TEMPLE 
WHERE NUMHI > 2;

-- 10
SELECT AVG(PRESU) AS PresupuestoMedio
FROM TDEPTO
WHERE PRESU > (SELECT AVG(PRESU) FROM TDEPTO);

-- 11
SELECT AVG(NUMHI) AS MediaNumHijos 
FROM TEMPLE 
WHERE NUMHI <= 2;

-- 12
SELECT NOMEM, (SALAR + COMIS) AS SalarioTotal
FROM TEMPLE 
WHERE FECIN > '1988-01-01' OR
(FECIN < '1988-01-01' AND
(SALAR + COMIS) < (SELECT 2 * MIN(SALAR + COMIS) 
FROM TEMPLE 
WHERE FECIN > '1988-01-01'))
ORDER BY NOMEM;