/*Claves Foráneas*/

/*CLAVE FORANEA - FK_NUMDE;*/


ALTER TABLE TEMPLE
ADD CONSTRAINT FK_NUMDE
FOREIGN KEY FK_NUMDE(NUMDE)
REFERENCES TDEPTO(NUMDE)
ON DELETE SET NULL
ON UPDATE CASCADE;


/*CLAVE FORANEA - FK_NUMCE;*/

ALTER TABLE TDEPTO
ADD CONSTRAINT FK_NUMCE
FOREIGN KEY FK_NUMCE(NUMCE)
REFERENCES TCENTR(NUMCE)
ON DELETE SET NULL
ON UPDATE CASCADE;


/*CLAVE FORANEA FK_DEPDE;*/

ALTER TABLE TDEPTO
ADD CONSTRAINT FK_DEPDE
FOREIGN KEY FK_DEPDE(DEPDE)
REFERENCES TDEPTO(NUMDE)
ON DELETE SET NULL
ON UPDATE CASCADE;


/*CLAVE FORANEA FK_DEPDE;*/

ALTER TABLE TDEPTO
ADD CONSTRAINT FK_DIREC
FOREIGN KEY FK_DIREC(DIREC)
REFERENCES TEMPLE(NUMEM)
ON DELETE SET NULL
ON UPDATE CASCADE;